### ISSUE TITLE
给个编译步骤，demo站点，截图？

### ISSUE THREAD

**Issue by pizixi** [glennliao/bookmark#1]

**Comment by pizixi** [comment]
跑起来了

**Comment by pizixi** [comment]
建议参考参考这个项目：https://github.com/luchenqun/my-bookmark

**Comment by glennliao** [comment]
> 建议参考参考这个项目：https://github.com/luchenqun/my-bookmark

主要功能上其实最后应该都会差不多的。
demo、截图、docker运行 因为这几天刚创建这个库， 还没处理

**Comment by glennliao** [comment]
> > 建议参考参考这个项目：https://github.com/luchenqun/my-bookmark
> 
> 主要功能上其实最后应该都会差不多的。 demo、截图、docker运行 因为这几天刚创建这个库， 还没处理

之前只是本地git的 apijson-go 试水项目

**Comment by pizixi** [comment]
关注了，啥时候能支持批量导入书签还有搜索书签 功能，这两个功能感觉很关键

**Comment by glennliao** [comment]
导入 浏览器导出的html书签 应该会在这个端午节后可用；搜索的话，目前可以搜索（右下角搜索图标），不过现在只是url和title的includes搜索。
