### ISSUE TITLE
修改localstorage中的token的key，防止可其他冲突导致报错

### ISSUE THREAD

**Issue by nextyancc** [glennliao/bookmark#10]
先 init，生成配置文件后，改了配置文件中的canReg 为 true，然后启动程序，页面没有出现注册按钮，而且还报未知错误是什么原因
![image](https://github.com/glennliao/bookmark/assets/131517244/26ff3801-cac7-435a-a518-7a978cc4112c)

**Comment by glennliao** [comment]
@nextyancc 你这个应该是 localStorage存在着 token 这个key，是别的系统留下来的，导致这边jwt解析失败了。可以去把它清除掉即可。

**Comment by nextyancc** [comment]
好的，之前确实使用了一个库，现在重新初始化了
