### ISSUE TITLE
这个home是不是跟书签功能重叠了

### ISSUE THREAD

**Issue by pizixi** [glennliao/bookmark#18]
好久不见有更新了，已经离不开这个系统了，请问接下来有什么更新计划呢
建议note功能把较长的文章自动折叠起来，点击更多再把文章展示全，方便观看

**Comment by glennliao** [comment]
home 主要是用来做入口使用，例如自己搭建的一些服务和常用的网页。
这个功能其实会和boommark的⭐页面的tag显示有重合。 
 

其实主要还是下一步想做成类似这样的
![image](https://github.com/glennliao/bookmark/assets/14543369/c6ad972b-1ee1-4be9-9d70-c229def5b27e)

这样一些常用的都可以放这里， 然后还可以就在home中切换打开， 不用开多标签

**Comment by glennliao** [comment]
note 过长的可以，放在下次更新

**Comment by pizixi** [comment]
期待ing
