### ISSUE TITLE
批量获取图标+分类展示书签个数+书签默认时间排序+搜索书签能显示分类信息/书签操作+页面展示bug+备忘录？

### ISSUE THREAD

**Issue by pizixi** [glennliao/bookmark#2]
上次提的导入已经可以用了，准备迁移过来了，毕竟go写的+sqlite部署起来太方便了，感谢大佬，另外有几点小建议，希望大佬酌情考虑
1、批量导入的书签图标能不能自动获取一下，目前好像都是名称的首字母代替的
2、分类栏能否在名称后面展示该分类栏下的书签个数，这样展示起来比较直观
3、书签展示页面（搜索结果页面）新增的书签放在前面是不是合理一点（目前同一个分类多个书签好像是按照书签添加时间升序排序的）
4、是否考虑增加对搜索书签编辑和删除的功能，书签比较多，也不知道放在哪，搜索出来之后不能操作，有点难受
5、当同一个分类下书签过多时，底部导航栏 没有自动下沉，导致跟书签框重叠，另外手机端每行只能显示一个书签，右边空出来很多有点不协调
6、希望大佬能坚持更新，增加更丰富的功能，比如类似隔壁的 备忘功能（当然不是刚需）
我来在各个群里给大佬推广推广项目

**Comment by glennliao** [comment]
@pizixi “当同一个分类下书签过多时，底部导航栏 没有自动下沉，导致跟书签框重叠”  这句可以截图看下吗

**Comment by pizixi** [comment]
@glennliao 
![image](https://github.com/glennliao/bookmark/assets/56673215/026da3b5-22c3-4619-a314-8cc43938946d)

**Comment by pizixi** [comment]
精辟

**Comment by glennliao** [comment]
@pizixi 今天我先处理下3和5
 
1.书签图标的话，应该会增加一个批量获取图标的操作按钮， 用于更新icon为空的书签， 然后还有一个批量更新@import标记的书签的按钮
（目前显示第一个是图标为空的默认显示标题的第一个字符）
2. 这个过两天更新下
4. 我先在显示中加上书签所在分类信息， 后续再加上直接编辑和操作
6. 有类似备忘录的功能计划的

**Comment by glennliao** [comment]
后续的不同内容的点还是分不同issue来写吧，方便进度跟踪 (●'◡'●)

**Comment by pizixi** [comment]
好的，效率真高啊，发现一个问题，无法添加不受信证书的url，报错信息如下：
Get "https://192.168.1.36/ui": x509: certificate signed by unknown authority 1. Get "https://192.168.1.36/ui": x509: certificate signed by unknown authority
   1).  github.com/gogf/gf/v2/util/gutil.Try.func1
        github.com/gogf/gf/v2@v2.4.4/util/gutil/gutil.go:36
   2).  runtime.gopanic
        runtime/panic.go:884
   3).  github.com/glennliao/apijson-go/drivers/goframe/web.(*GF).CommonResponse.func1.1
        github.com/glennliao/apijson-go@v0.2.0-beta8/drivers/goframe/web/gf.go:108
   4).  github.com/gogf/gf/v2/util/gutil.Try
        github.com/gogf/gf/v2@v2.4.4/util/gutil/gutil.go:40
   5).  github.com/gogf/gf/v2/frame/g.Try
        github.com/gogf/gf/v2@v2.4.4/frame/g/g_func.go:72
   6).  github.com/glennliao/apijson-go/drivers/goframe/web.(*GF).CommonResponse.func1
        github.com/glennliao/apijson-go@v0.2.0-beta8/drivers/goframe/web/gf.go:88
   7).  github.com/gogf/gf/v2/net/ghttp.(*middleware).callHandlerFunc.func1
        github.com/gogf/gf/v2@v2.4.4/net/ghttp/ghttp_request_middleware.go:131
   8).  github.com/gogf/gf/v2/net/ghttp.niceCallFunc
        github.com/gogf/gf/v2@v2.4.4/net/ghttp/ghttp_func.go:61
   9).  github.com/gogf/gf/v2/net/ghttp.(*middleware).callHandlerFunc
        github.com/gogf/gf/v2@v2.4.4/net/ghttp/ghttp_request_middleware.go:129
   10). github.com/gogf/gf/v2/net/ghttp.(*middleware).Next.func1.4
        github.com/gogf/gf/v2@v2.4.4/net/ghttp/ghttp_request_middleware.go:90
   11). github.com/gogf/gf/v2/net/ghttp.(*middleware).Next.func1
        github.com/gogf/gf/v2@v2.4.4/net/ghttp/ghttp_request_middleware.go:89
   12). github.com/gogf/gf/v2/util/gutil.TryCatch
        github.com/gogf/gf/v2@v2.4.4/util/gutil/gutil.go:56
   13). github.com/gogf/gf/v2/net/ghttp.(*middleware).Next
        github.com/gogf/gf/v2@v2.4.4/net/ghttp/ghttp_request_middleware.go:49
   14). github.com/glennliao/bookmark/app.Auth
        github.com/glennliao/bookmark/app/middleware.go:82
   15). github.com/gogf/gf/v2/net/ghttp.(*middleware).Next.func1.1
        github.com/gogf/gf/v2@v2.4.4/net/ghttp/ghttp_request_middleware.go:55
   16). github.com/gogf/gf/v2/net/ghttp.(*middleware).Next.func1
        github.com/gogf/gf/v2@v2.4.4/net/ghttp/ghttp_request_middleware.go:54
   17). github.com/glennliao/bookmark/app.Cors
        github.com/glennliao/bookmark/app/middleware.go:89
   18). github.com/gogf/gf/v2/net/ghttp.internalMiddlewareServerTracing
        github.com/gogf/gf/v2@v2.4.4/net/ghttp/ghttp_middleware_tracing.go:79
   19). github.com/gogf/gf/v2/net/ghttp.(*middleware).Next.func1.5
        github.com/gogf/gf/v2@v2.4.4/net/ghttp/ghttp_request_middleware.go:96
   20). github.com/gogf/gf/v2/net/ghttp.(*middleware).Next.func1
        github.com/gogf/gf/v2@v2.4.4/net/ghttp/ghttp_request_middleware.go:95
   21). github.com/gogf/gf/v2/net/ghttp.(*Server).ServeHTTP
        github.com/gogf/gf/v2@v2.4.4/net/ghttp/ghttp_server_handler.go:132
   22). net/http.HandlerFunc.ServeHTTP
        net/http/server.go:2109
   23). net/http.serverHandler.ServeHTTP
        net/http/server.go:2947
   24). net/http.(*conn).serve
        net/http/server.go:1991
   25). runtime.goexit
        runtime/asm_amd64.s:1594

**Comment by glennliao** [comment]
@pizixi  已加忽略 tls 错误

**Comment by pizixi** [comment]
@glennliao 还有个问题比较棘手，我bookmark 部署在云上，我想收藏一些内网网址(云服务器是访问不到的)，好像没法添加，之前批量导入的那些内网网站的 那个图标也显示不了，可有啥解决方案？报错信息如下：
runtime error: invalid memory address or nil pointer dereference 1. runtime error: invalid memory address or nil pointer dereference
   1).  github.com/gogf/gf/v2/util/gutil.Try.func1
        github.com/gogf/gf/v2@v2.4.4/util/gutil/gutil.go:36
   2).  runtime.gopanic
        runtime/panic.go:884
   3).  runtime.panicmem
        runtime/panic.go:260
   4).  runtime.sigpanic
        runtime/signal_unix.go:839
   5).  github.com/glennliao/bookmark/app/util/fetchurl.FetchURLMeta
        github.com/glennliao/bookmark/app/util/fetchurl/fetchurl.go:49
   6).  github.com/glennliao/bookmark/app.glob..func2
        github.com/glennliao/bookmark/app/func.go:84
   7).  github.com/glennliao/apijson-go/query.(*funcNode).fetch
        github.com/glennliao/apijson-go@v0.2.0-beta8/query/node_func.go:47
   8).  github.com/glennliao/apijson-go/query.(*Node).fetch
        github.com/glennliao/apijson-go@v0.2.0-beta8/query/node.go:300
   9).  github.com/glennliao/apijson-go/query.(*Query).fetch
        github.com/glennliao/apijson-go@v0.2.0-beta8/query/query.go:157
   10). github.com/glennliao/apijson-go/query.(*Query).Result
        github.com/glennliao/apijson-go@v0.2.0-beta8/query/query.go:107
   11). github.com/glennliao/apijson-go/drivers/goframe/web.(*GF).Get
        github.com/glennliao/apijson-go@v0.2.0-beta8/drivers/goframe/web/gf.go:59
   12). github.com/glennliao/apijson-go/drivers/goframe/web.(*GF).CommonResponse.func1.1
        github.com/glennliao/apijson-go@v0.2.0-beta8/drivers/goframe/web/gf.go:90
   13). github.com/gogf/gf/v2/util/gutil.Try
        github.com/gogf/gf/v2@v2.4.4/util/gutil/gutil.go:40
   14). github.com/gogf/gf/v2/frame/g.Try
        github.com/gogf/gf/v2@v2.4.4/frame/g/g_func.go:72
   15). github.com/glennliao/apijson-go/drivers/goframe/web.(*GF).CommonResponse.func1
        github.com/glennliao/apijson-go@v0.2.0-beta8/drivers/goframe/web/gf.go:88
   16). github.com/gogf/gf/v2/net/ghttp.(*middleware).callHandlerFunc.func1
        github.com/gogf/gf/v2@v2.4.4/net/ghttp/ghttp_request_middleware.go:131
   17). github.com/gogf/gf/v2/net/ghttp.niceCallFunc
        github.com/gogf/gf/v2@v2.4.4/net/ghttp/ghttp_func.go:61
   18). github.com/gogf/gf/v2/net/ghttp.(*middleware).callHandlerFunc
        github.com/gogf/gf/v2@v2.4.4/net/ghttp/ghttp_request_middleware.go:129
   19). github.com/gogf/gf/v2/net/ghttp.(*middleware).Next.func1.4
        github.com/gogf/gf/v2@v2.4.4/net/ghttp/ghttp_request_middleware.go:90
   20). github.com/gogf/gf/v2/net/ghttp.(*middleware).Next.func1
        github.com/gogf/gf/v2@v2.4.4/net/ghttp/ghttp_request_middleware.go:89
   21). github.com/gogf/gf/v2/util/gutil.TryCatch
        github.com/gogf/gf/v2@v2.4.4/util/gutil/gutil.go:56
   22). github.com/gogf/gf/v2/net/ghttp.(*middleware).Next
        github.com/gogf/gf/v2@v2.4.4/net/ghttp/ghttp_request_middleware.go:49
   23). github.com/glennliao/bookmark/app.Auth
        github.com/glennliao/bookmark/app/middleware.go:82
   24). github.com/gogf/gf/v2/net/ghttp.(*middleware).Next.func1.1
        github.com/gogf/gf/v2@v2.4.4/net/ghttp/ghttp_request_middleware.go:55
   25). github.com/gogf/gf/v2/net/ghttp.(*middleware).Next.func1
        github.com/gogf/gf/v2@v2.4.4/net/ghttp/ghttp_request_middleware.go:54
   26). github.com/glennliao/bookmark/app.Cors
        github.com/glennliao/bookmark/app/middleware.go:89
   27). github.com/gogf/gf/v2/net/ghttp.internalMiddlewareServerTracing
        github.com/gogf/gf/v2@v2.4.4/net/ghttp/ghttp_middleware_tracing.go:79
   28). github.com/gogf/gf/v2/net/ghttp.(*middleware).Next.func1.5
        github.com/gogf/gf/v2@v2.4.4/net/ghttp/ghttp_request_middleware.go:96
   29). github.com/gogf/gf/v2/net/ghttp.(*middleware).Next.func1
        github.com/gogf/gf/v2@v2.4.4/net/ghttp/ghttp_request_middleware.go:95
   30). github.com/gogf/gf/v2/net/ghttp.(*Server).ServeHTTP
        github.com/gogf/gf/v2@v2.4.4/net/ghttp/ghttp_server_handler.go:132
   31). net/http.HandlerFunc.ServeHTTP
        net/http/server.go:2109
   32). net/http.serverHandler.ServeHTTP
        net/http/server.go:2947
   33). net/http.(*conn).serve
        net/http/server.go:1991
   34). runtime.goexit
        runtime/asm_amd64.s:1594

**Comment by glennliao** [comment]
@pizixi 你新开一个issue吧，再把你说的图标问题 截图或其他方式再具体描述下。 今晚我更新下，加个可手动录入书签信息

**Comment by pizixi** [comment]
好的，我先把这个关了

**Comment by glennliao** [comment]
@pizixi  最开始提的几个东西还没完毕的，不急着关。   主要是说每个不同的内容单独一个issue， 这样方便跟踪 每个的进度。 多个放在一起的话， 不好单独区分。  特别是分开时候可以关联到project的看板中

**Comment by pizixi** [comment]
@glennliao 好的，我单独提了一个

**Comment by pizixi** [comment]
排序问题啥时候能更新哈

**Comment by glennliao** [comment]
@pizixi 可以了，上次更新漏了子分类的书签排序了。
