### ISSUE TITLE
请问是否有配置能将acess校验临时放开

### ISSUE THREAD

**Issue by zxzxasas11** [glennliao/bookmark#23]
我需要创建一个内部使用的通用的应用,能否直接通过标表名查询,不去设置access.json 文件

**Comment by glennliao** [comment]
https://github.com/glennliao/bookmark/blob/6de4be9b1e80e441e749138de6cac7dcddd3ba7a/app/app.go#L15

在这里写个Provider， 可以从数据库读取所有表， 然后返回[]Access, 即可实现数据库所有表默认可用。 你是在用apijson-go吗， 而不是这个书签系统。

**Comment by glennliao** [comment]
如果想使用 apijson-go的话， 可以加下我， 微信 huanznian

**Comment by zxzxasas11** [comment]
> https://github.com/glennliao/bookmark/blob/6de4be9b1e80e441e749138de6cac7dcddd3ba7a/app/app.go#L15
> 
> 在这里写个Provider， 可以从数据库读取所有表， 然后返回[]Access, 即可实现数据库所有表默认可用。 你是在用apijson-go吗， 而不是这个书签系统。

是的,想基于apijson-go 开发一个低代码的数据看板 .

**Comment by glennliao** [comment]
你加下我wx huanznian
