### ISSUE TITLE
内网图标无法显示问题

### ISSUE THREAD

**Issue by pizixi** [glennliao/bookmark#6]
场景：bookmark 部署在云服务器上，添加了一个公司内网的网站 
地址
http://192.168.1.46:8080/login?from=%2F
图标
http://192.168.1.46:8080/favicon.ico

结果：公司电脑上浏览器访问bookmark时看不到上面这个url的图标，是不是因为云服务器访问不了这个图标url？

截图如下：
![image](https://github.com/glennliao/bookmark/assets/56673215/13febd7f-f458-407b-a723-0d522758b060)

**Comment by glennliao** [comment]
图标是直接浏览器去访问 图标地址的， 你试下浏览器直接访问 图标地址看能不能打开， 不能的话， 应该就是图标的url地址不正确，可以的话你截图下浏览器的console

**Comment by pizixi** [comment]
![image](https://github.com/glennliao/bookmark/assets/56673215/ab90269b-46e9-4709-a6c7-d4c8a8e35898)

![image](https://github.com/glennliao/bookmark/assets/56673215/a631d0d5-f54b-4c7c-bd3a-51798ed509cc)

**Comment by pizixi** [comment]
很奇怪，貌似确实没有经过服务端，是不是跟http协议有关系

**Comment by pizixi** [comment]
我把bookmark放我我公司的pc机上跑，同一个书签，正常显示
![image](https://github.com/glennliao/bookmark/assets/56673215/13b178a3-4ace-4df2-a215-474c655ef5c2)

**Comment by pizixi** [comment]
看到报错信息了：The page at 'https://******/#/' was loaded over HTTPS, but requested an insecure image 'http://192.168.1.46:8080/favicon.ico'. This request has been blocked; the content must be served over HTTPS.

**Comment by glennliao** [comment]
> 看到报错信息了：The page at 'https://******/#/' was loaded over HTTPS, but requested an insecure image 'http://192.168.1.46:8080/favicon.ico'. This request has been blocked; the content must be served over HTTPS.

这个就是因为https站点无法访问http的资源的问题了，我看下今晚弄个别的方案 来曲线救国 显示图标吧。

**Comment by glennliao** [comment]
@pizixi 点击图标输入框右边的图标预览区 可手动上传图片作为图标

**Comment by pizixi** [comment]
也可以直接使用官方的图标链接，这样省得维护了。比如Jenkins：https://www.jenkins.io/favicon.ico
